import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Content from "../components/content";
import Footer from "../components/footer";
import Navbar from "../components/navbar";
import Drumkits from "../components/drumkits";

const drumkitJson = [
  {
    title: "325 melodie+compositions made by me & some friends :)",
    upvotes: "9",
    link: "https://www.dropbox.com/sh/we9y2cgembtv76m/AAAPcsimkzTr7cJq2k_vriOua?dl=0",
    reddit:
      "https://www.reddit.com/r/Drumkits/comments/whoy5n/325_melodiecompositions_made_by_me_some_friends/",
  },
  {
    title: 'OFFICIAL "BALD!" SNARE',
    upvotes: "27",
    link: "https://drive.google.com/file/d/1mRTcBFP30gCPsppWAS0M3bs8qYCoR64R/view?usp=sharing",
    reddit:
      "https://www.reddit.com/r/Drumkits/comments/whhu60/official_bald_snare/",
  },
  {
    title: "325 melodie+compositions made by me & some friends :)",
    upvotes: "9",
    link: "https://www.dropbox.com/sh/we9y2cgembtv76m/AAAPcsimkzTr7cJq2k_vriOua?dl=0",
    reddit:
      "https://www.reddit.com/r/Drumkits/comments/whoy5n/325_melodiecompositions_made_by_me_some_friends/",
  },
  {
    title: 'OFFICIAL "BALD!" SNARE',
    upvotes: "27",
    link: "https://drive.google.com/file/d/1mRTcBFP30gCPsppWAS0M3bs8qYCoR64R/view?usp=sharing",
    reddit:
      "https://www.reddit.com/r/Drumkits/comments/whhu60/official_bald_snare/",
  },
  {
    title: "325 melodie+compositions made by me & some friends :)",
    upvotes: "9",
    link: "https://www.dropbox.com/sh/we9y2cgembtv76m/AAAPcsimkzTr7cJq2k_vriOua?dl=0",
    reddit:
      "https://www.reddit.com/r/Drumkits/comments/whoy5n/325_melodiecompositions_made_by_me_some_friends/",
  },
  {
    title: 'OFFICIAL "BALD!" SNARE',
    upvotes: "27",
    link: "https://drive.google.com/file/d/1mRTcBFP30gCPsppWAS0M3bs8qYCoR64R/view?usp=sharing",
    reddit:
      "https://www.reddit.com/r/Drumkits/comments/whhu60/official_bald_snare/",
  },
  {
    title: "325 melodie+compositions made by me & some friends :)",
    upvotes: "9",
    link: "https://www.dropbox.com/sh/we9y2cgembtv76m/AAAPcsimkzTr7cJq2k_vriOua?dl=0",
    reddit:
      "https://www.reddit.com/r/Drumkits/comments/whoy5n/325_melodiecompositions_made_by_me_some_friends/",
  },
  {
    title: 'OFFICIAL "BALD!" SNARE',
    upvotes: "27",
    link: "https://drive.google.com/file/d/1mRTcBFP30gCPsppWAS0M3bs8qYCoR64R/view?usp=sharing",
    reddit:
      "https://www.reddit.com/r/Drumkits/comments/whhu60/official_bald_snare/",
  },
  {
    title: "325 melodie+compositions made by me & some friends :)",
    upvotes: "9",
    link: "https://www.dropbox.com/sh/we9y2cgembtv76m/AAAPcsimkzTr7cJq2k_vriOua?dl=0",
    reddit:
      "https://www.reddit.com/r/Drumkits/comments/whoy5n/325_melodiecompositions_made_by_me_some_friends/",
  },
  {
    title: 'OFFICIAL "BALD!" SNARE',
    upvotes: "27",
    link: "https://drive.google.com/file/d/1mRTcBFP30gCPsppWAS0M3bs8qYCoR64R/view?usp=sharing",
    reddit:
      "https://www.reddit.com/r/Drumkits/comments/whhu60/official_bald_snare/",
  },
  {
    title: "325 melodie+compositions made by me & some friends :)",
    upvotes: "9",
    link: "https://www.dropbox.com/sh/we9y2cgembtv76m/AAAPcsimkzTr7cJq2k_vriOua?dl=0",
    reddit:
      "https://www.reddit.com/r/Drumkits/comments/whoy5n/325_melodiecompositions_made_by_me_some_friends/",
  },
  {
    title: 'OFFICIAL "BALD!" SNARE',
    upvotes: "27",
    link: "https://drive.google.com/file/d/1mRTcBFP30gCPsppWAS0M3bs8qYCoR64R/view?usp=sharing",
    reddit:
      "https://www.reddit.com/r/Drumkits/comments/whhu60/official_bald_snare/",
  },
];

export default function Home() {
  return (
    <div>
      <Head>
        <title>Drumkits-DL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col h-screen justify-between bg-primary">
        <div className="sticky top-0 blue">
          <Navbar />
        </div>
        <div className="h-3/4">
          {/* <Content /> */}
          <Drumkits drumkits={drumkitJson} />
        </div>
        <Footer />
      </div>
    </div>
  );
}
